package main

import (
	"os"
	"strconv"

	"execray.tracer/internal/tracer"
	logrus "github.com/sirupsen/logrus"

	"github.com/cilium/ebpf/rlimit"
)

// This struct is generated by bpf2go

func main() {
	// Subscribe to signals for graceful shutdown.
	log := logrus.New()
	log.SetLevel(logrus.DebugLevel)

	if len(os.Args) < 2 {
		log.Fatalf("Usage: %s <pid>", os.Args[0])
	}
	pid, err := strconv.Atoi(os.Args[1])
	if err != nil {
		log.Fatalf("Invalid PID: %v", err)
	}
	log.Printf("Attaching to PID: %d", pid)
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal("Failed to remove rlimit memlock:", err)
	}
	tracer.TraceDaemon(log, uint32(pid))

}
